[build]
  base = "./"
  publish = ".vuepress/dist"
  command = "yarn build"

# Sets our asset optimization
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = false
[build.processing.images]
  compress = true

# Caches our images for 1 year
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirect to canonical location
[[redirects]]
  from = "https://blog.devwithlando.io"
  to = "https://lando.dev/blog"
  status = 301
  force = true
[[redirects]]
  from = "https://blog.devwithlando.io/"
  to = "https://lando.dev/blog"
  status = 301
  force = true
[[redirects]]
  from = "https://blog.devwithlando.io/*"
  to = "https://lando.dev/blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://blog.lando.dev"
  to = "https://lando.dev/blog"
  status = 301
  force = true
[[redirects]]
  from = "https://blog.lando.dev/"
  to = "https://lando.dev/blog"
  status = 301
  force = true
[[redirects]]
  from = "https://blog.lando.dev/*"
  to = "https://lando.dev/blog/:splat"
  status = 301
  force = true
 [[redirects]]
  from = "https://blog.lndo.io/"
  to = "https://lando.dev/blog"
  status = 301
  force = true
[[redirects]]
  from = "https://blog.lndo.io"
  to = "https://lando.dev/blog"
  status = 301
  force = true
[[redirects]]
  from = "https://blog.lndo.io/*"
  to = "https://lando.dev/blog/:splat"
  status = 301
  force = true

# Rewrites
[[redirects]]
  from = "/"
  to = "/blog"
  status = 200
[[redirects]]
  from = "/blog/*"
  to = "/:splat"
  status = 200
